Repository cocoding-ss/apjung-backend, pull requests merged in 2020-12, with the labels that each got.

#108 쇼핑몰 리스트 가져오기 API 개발
  api/build.gradle
  api/src/docs/asciidoc/index.adoc
  api/src/docs/asciidoc/shop.adoc
  api/src/main/java/me/apjung/backend/api/ShopController.java
  api/src/main/java/me/apjung/backend/api/locator/ShopSearchServiceLocator.java
  api/src/main/java/me/apjung/backend/domain/Base/BaseEntity.java
  api/src/main/java/me/apjung/backend/domain/Base/ViewStats.java
  api/src/main/java/me/apjung/backend/domain/shop/Shop.java
  api/src/main/java/me/apjung/backend/dto/request/ShopRequest.java
  api/src/main/java/me/apjung/backend/dto/response/ShopResponse.java
  api/src/main/java/me/apjung/backend/dto/vo/Thumbnail.java
  api/src/main/java/me/apjung/backend/repository/Shop/ShopRepository.java
  api/src/main/java/me/apjung/backend/repository/Shop/ShopRepositoryCustom.java
  api/src/main/java/me/apjung/backend/repository/Shop/ShopRepositoryImpl.java
  api/src/main/java/me/apjung/backend/repository/User/UserRepositoryImpl.java
  api/src/main/java/me/apjung/backend/repository/shop/CustomShopRepository.java
  api/src/main/java/me/apjung/backend/repository/shop/ShopRepository.java
  api/src/main/java/me/apjung/backend/repository/shop/ShopRepositoryImpl.java
  api/src/main/java/me/apjung/backend/service/shop/ShopService.java
  api/src/main/java/me/apjung/backend/service/shop/ShopServiceImpl.java
  api/src/main/java/me/apjung/backend/service/shop/search/ShopSearchOrderByCreatedByService.java
  api/src/main/java/me/apjung/backend/service/shop/search/ShopSearchOrderByNameService.java
  api/src/main/java/me/apjung/backend/service/shop/search/ShopSearchOrderByStrategy.java
  api/src/main/java/me/apjung/backend/service/shop/search/ShopSearchService.java
  api/src/main/resources-test/application.yaml
  api/src/rest/ShopController.http
  api/src/test/java/me/apjung/backend/AbstractDataJpaTest.java
  api/src/test/java/me/apjung/backend/MvcTest.java
  api/src/test/java/me/apjung/backend/api/ShopControllerTest.java
  api/src/test/java/me/apjung/backend/api/locator/ShopSearchServiceLocatorTest.java
  api/src/test/java/me/apjung/backend/dto/response/ShopResponseTest.java
  api/src/test/java/me/apjung/backend/dto/vo/ThumbnailTest.java
  api/src/test/java/me/apjung/backend/repository/shop/ShopRepositoryTest.java
  api/src/test/java/me/apjung/backend/service/shop/search/ShopSearchOrderByNameServiceTest.java
  api/src/test/java/me/apjung/backend/service/shop/search/ShopSearchOrderByStrategyTest.java
  api/src/test/resources/data.sql
  readme.md
Labels: 기능, 리뷰요청

#110 회원가입 API 이메일 중복여부 예외처리 필요
  api/src/docs/asciidoc/auth.adoc
  api/src/docs/asciidoc/shop.adoc
  api/src/main/java/me/apjung/backend/api/AuthCallbackController.java
  api/src/main/java/me/apjung/backend/api/AuthController.java
  api/src/main/java/me/apjung/backend/api/advisor/AuthExceptionHandler.java
  api/src/main/java/me/apjung/backend/api/advisor/BaseExceptionHandler.java
  api/src/main/java/me/apjung/backend/api/exception/DuplicatedEmailException.java
  api/src/main/java/me/apjung/backend/component/CustomMessageSourceResolver/CustomMessageSourceResolver.java
  api/src/main/java/me/apjung/backend/config/WebMvcConfig.java
  api/src/main/java/me/apjung/backend/dto/response/ErrorResponse.java
  api/src/main/java/me/apjung/backend/repository/user/UserRepository.java
  api/src/main/java/me/apjung/backend/repository/user/UserRepositoryCustom.java
  api/src/main/java/me/apjung/backend/repository/user/UserRepositoryImpl.java
  api/src/main/java/me/apjung/backend/service/Security/CustomUserDetailsService.java
  api/src/main/java/me/apjung/backend/service/auth/AuthService.java
  api/src/main/java/me/apjung/backend/service/auth/AuthServiceImpl.java
  api/src/main/resources/db/migration/V20201205001522__Create_Index_User_Email.sql
  api/src/main/resources/locale/exception/message_en.yaml
  api/src/main/resources/locale/exception/message_ko.yaml
  api/src/test/java/me/apjung/backend/Mock/WithCustomMockUserSecurityContextFactory.java
  api/src/test/java/me/apjung/backend/MvcTest.java
  api/src/test/java/me/apjung/backend/api/AuthControllerTest.java
  api/src/test/java/me/apjung/backend/repository/user/UserRepositoryTest.java
  api/src/test/java/me/apjung/backend/service/auth/AuthServiceImplTest.java
Labels: 기능, 리뷰요청, 작업중

#114 태그 기능 동작 확인, DB 데이터 의존성 있는 테스트 Disable함 #105
  api/src/main/java/me/apjung/backend/domain/shop/Shop.java
  api/src/main/java/me/apjung/backend/domain/shop/ShopTag.java
  api/src/main/java/me/apjung/backend/domain/tag/Tag.java
  api/src/main/java/me/apjung/backend/dto/request/ShopRequest.java
  api/src/main/java/me/apjung/backend/repository/tag/TagRepository.java
  api/src/main/java/me/apjung/backend/service/shop/ShopServiceImpl.java
  api/src/main/resources/db/migration/V20201210215824__Create_Tags_Table.sql
  api/src/main/resources/db/migration/V20201210215843__Create_Shop_Tags_Table.sql
  api/src/rest/ShopController.http
  api/src/test/java/me/apjung/backend/api/AuthControllerTest.java
  api/src/test/java/me/apjung/backend/api/ShopControllerTest.java
  api/src/test/java/me/apjung/backend/mock/MockUser.java
  api/src/test/java/me/apjung/backend/repository/shop/ShopRepositoryTest.java
  api/src/test/java/me/apjung/backend/service/shop/ShopServiceImplTest.java
Labels: 리뷰요청

#118 쇼핑몰 인증 프로세스 추가 #116
  api/src/main/java/me/apjung/backend/api/ShopController.java
  api/src/main/java/me/apjung/backend/domain/file/File.java
  api/src/main/java/me/apjung/backend/domain/shop/Shop.java
  api/src/main/java/me/apjung/backend/domain/shop/ShopSafeLevel.java
  api/src/main/java/me/apjung/backend/domain/shop/ShopSafeLog.java
  api/src/main/java/me/apjung/backend/dto/request/ShopRequest.java
  api/src/main/java/me/apjung/backend/dto/response/ShopResponse.java
  api/src/main/java/me/apjung/backend/repository/shop/ShopSafeLogRepository.java
  api/src/main/java/me/apjung/backend/service/shop/ShopService.java
  api/src/main/java/me/apjung/backend/service/shop/ShopServiceImpl.java
  api/src/main/resources/db/migration/V20201213220202__Create_Shops_Auth_Logs_Table.sql
  api/src/main/resources/db/migration/V20201214213005__Shop_Table_Add_Safe_Columns.sql
  api/src/rest/ShopController.http
  api/src/test/java/me/apjung/backend/MvcTest.java
  api/src/test/java/me/apjung/backend/api/ShopControllerTest.java
  api/src/test/java/me/apjung/backend/service/shop/ShopServiceImplTest.java
Labels: 리뷰요청

#120 issue#107
  api/src/docs/asciidoc/shop.adoc
  api/src/main/java/me/apjung/backend/api/ShopController.java
  api/src/main/java/me/apjung/backend/domain/base/ViewStats.java
  api/src/main/java/me/apjung/backend/domain/shop/Shop.java
  api/src/main/java/me/apjung/backend/domain/shop/ShopViewLog.java
  api/src/main/java/me/apjung/backend/domain/shop/ShopViewStats.java
  api/src/main/java/me/apjung/backend/dto/request/ShopRequest.java
  api/src/main/java/me/apjung/backend/dto/response/ShopResponse.java
  api/src/main/java/me/apjung/backend/repository/shop_view_stats/ShopViewStatsRepository.java
  api/src/main/java/me/apjung/backend/repository/shopviewlog/ShopViewLogRepository.java
  api/src/main/java/me/apjung/backend/service/shop/ShopService.java
  api/src/main/java/me/apjung/backend/service/shop/ShopServiceImpl.java
  api/src/main/java/me/apjung/backend/service/shop/search/ShopSearchOrderByCreatedByService.java
  api/src/main/java/me/apjung/backend/service/shop/search/ShopSearchOrderByNameService.java
  api/src/main/java/me/apjung/backend/service/shop/search/ShopSearchService.java
  api/src/main/resources-local/application.yaml
  api/src/main/resources/db/migration/V20201211042505__Drop_Column_Shops_Pv_Uv.sql
  api/src/main/resources/db/migration/V20201211042828__Create_Shops_View_Stats_Table.sql
  api/src/main/resources/db/migration/V20201211043925__Create_Shops_View_Logs_Table.sql
  api/src/main/resources/db/migration/V20201212185824__Rename_Shops_View_Logs_Column.sql
  api/src/main/resources/db/migration/V20201219161951__Create_Index_Shops_View_Logs_Search.sql
  api/src/rest/ShopController.http
  api/src/test/java/me/apjung/backend/MvcTest.java
  api/src/test/java/me/apjung/backend/api/AuthControllerTest.java
  api/src/test/java/me/apjung/backend/api/ShopControllerTest.java
  api/src/test/java/me/apjung/backend/dto/response/ShopResponseTest.java
  api/src/test/java/me/apjung/backend/repository/shop/ShopRepositoryTest.java
  api/src/test/java/me/apjung/backend/repository/shop_view_stats/ShopViewStatsRepositoryTest.java
  api/src/test/java/me/apjung/backend/repository/shopviewlog/ShopViewLogRepositoryTest.java
  api/src/test/java/me/apjung/backend/service/shop/ShopServiceImplTest.java
  api/src/test/java/me/apjung/backend/service/shop/search/ShopSearchOrderByNameServiceTest.java
Labels: 기능, 리뷰요청, 작업중

#124 기존 테스트 Mocking 작업
  api/src/main/java/me/apjung/backend/domain/user/role/Role.java
  api/src/main/java/me/apjung/backend/dto/response/AuthResponse.java
  api/src/main/java/me/apjung/backend/repository/role/RoleRepository.java
  api/src/main/java/me/apjung/backend/service/auth/AuthServiceImpl.java
  api/src/test/java/me/apjung/backend/MvcTest.java
  api/src/test/java/me/apjung/backend/api/AuthControllerTest.java
  api/src/test/java/me/apjung/backend/api/ShopControllerTest.java
  api/src/test/java/me/apjung/backend/mock/MockUser.java
  api/src/test/java/me/apjung/backend/mock/WithCustomMockUserSecurityContextFactory.java
Labels: 기능, 작업중

#126 @DataJpaTest 동작 개선
  api/build.gradle
  api/src/main/java/me/apjung/backend/property/JwtProps.java
  api/src/main/java/me/apjung/backend/property/SecurityProps.java
  api/src/main/java/me/apjung/backend/property/StorageProps.java
  api/src/main/resources-dev/jwt.yaml
  api/src/main/resources-dev/security.yaml
  api/src/main/resources-dev/storage.yaml
  api/src/main/resources-local/jwt.yaml
  api/src/main/resources-local/security.yaml
  api/src/main/resources-local/storage.yaml
  api/src/main/resources-prod/jwt.yaml
  api/src/main/resources-prod/security.yaml
  api/src/main/resources-prod/storage.yaml
  api/src/main/resources-test/jwt.yaml
  api/src/main/resources-test/security.yaml
  api/src/main/resources-test/storage.yaml
  api/src/main/resources/application-dev.yaml
  api/src/main/resources/application-prod.yaml
  api/src/main/resources/application-test.yaml
  api/src/main/resources/application.yaml
  api/src/main/resources/db/migration/V20201016093128__Create_User_Table.sql
  api/src/main/resources/db/migration/V20201016104024__Add_Column_Test_User_Table.sql
  api/src/main/resources/db/migration/V20201016104148__Delete_Column_Test_User_Table.sql
  api/src/main/resources/db/migration/V20201018030249__Update_User_Table_Add_Base_Columns.sql
  api/src/main/resources/db/migration/V20201020092912__Create_User_Role_Table.sql
  api/src/main/resources/db/migration/V20201020093336__Modify_User_Table_Column.sql
  api/src/main/resources/db/migration/V20201020094928__Insert_User_Role.sql
  api/src/main/resources/db/migration/V20201031180404__Create_Shop_Table.sql
  api/src/main/resources/db/migration/V20201205001522__Create_Index_User_Email.sql
  api/src/main/resources/db/migration/V20201209023110__Modify_Shop_Table_Datetime_Change.sql
  api/src/main/resources/db/migration/V20201211042505__Drop_Column_Shops_Pv_Uv.sql
  api/src/main/resources/db/migration/V20201211043925__Create_Shops_View_Logs_Table.sql
  api/src/main/resources/db/migration/V20201212185824__Rename_Shops_View_Logs_Column.sql
  api/src/main/resources/db/migration/V20201214213005__Shop_Table_Add_Safe_Columns.sql
  api/src/main/resources/db/migration/V20201219161951__Create_Index_Shops_View_Logs_Search.sql
  api/src/test/java/me/apjung/backend/IntegrationTest.java
  api/src/test/java/me/apjung/backend/JpaTest.java
  api/src/test/java/me/apjung/backend/MvcTest.java
  api/src/test/java/me/apjung/backend/component/custommessagesourceresolver/CustomMessageSourceResolverTest.java
  api/src/test/java/me/apjung/backend/component/mailservice/MailHandlerTest.java
  api/src/test/java/me/apjung/backend/component/randomstringbuilder/RandomStringBuilderTest.java
  api/src/test/java/me/apjung/backend/config/WevMvcConfigTest.java
  api/src/test/java/me/apjung/backend/property/AppPropsTest.java
  api/src/test/java/me/apjung/backend/property/JwtPropsTest.java
  api/src/test/java/me/apjung/backend/property/SecurityPropsTest.java
  api/src/test/java/me/apjung/backend/repository/shop/ShopRepositoryTest.java
  api/src/test/java/me/apjung/backend/repository/shop_view_stats/ShopViewStatsRepositoryTest.java
  api/src/test/java/me/apjung/backend/repository/shopviewlog/ShopViewLogRepositoryTest.java
  api/src/test/java/me/apjung/backend/repository/user/UserRepositoryTest.java
Labels: 기능, 작업중

#129 쇼핑몰 검색 및 리스팅 기능 개선
  api/src/docs/asciidoc/shop.adoc
  api/src/main/java/me/apjung/backend/domain/shop/ShopTag.java
  api/src/main/java/me/apjung/backend/repository/shop/ShopRepositoryImpl.java
  api/src/main/java/me/apjung/backend/repository/shopviewstats/ShopViewStatsRepository.java
  api/src/main/java/me/apjung/backend/repository/tag/TagRepository.java
  api/src/main/java/me/apjung/backend/service/shop/ShopServiceImpl.java
  api/src/main/resources/db/migration/V20201227043405__Create_Index_Tag_Name.sql
  api/src/test/java/me/apjung/backend/MvcTest.java
  api/src/test/java/me/apjung/backend/api/ShopControllerTest.java
  api/src/test/java/me/apjung/backend/repository/shop/ShopRepositoryTest.java
  api/src/test/java/me/apjung/backend/repository/shopviewlog/ShopViewLogRepositoryTest.java
  api/src/test/java/me/apjung/backend/repository/shopviewstats/ShopViewStatsRepositoryTest.java
  api/src/test/java/me/apjung/backend/repository/tag/TagRepositoryTest.java
  api/src/test/java/me/apjung/backend/service/shop/ShopServiceImplTest.java
  api/src/test/java/me/apjung/backend/service/shop/search/ShopSearchOrderByNameServiceTest.java
Labels: 기능, 리뷰요청, 작업중
